// provided.js - generated by ephemient/aoc2021/Kotlin benchmarks, 2021-12-09 09:47:03.535945229

var providedBenchmarks = ["jsBench","jvmBench"];

var providedBenchmarkStore = {
  "jsBench": [
    {
      "benchmark": "com.github.ephemient.aoc2021.Day1Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 6.236856708569458,
        "scoreError": 0.009290480275280948,
        "scoreConfidence": [
          6.227566228294177,
          6.246147188844739
        ],
        "scorePercentiles": {
          "0.00": 6.230807920362838,
          "25.00": 6.230807920362838,
          "50.00": 6.2335594663545875,
          "75.00": 6.246202738990948,
          "90.00": 6.246202738990948,
          "99.00": 6.246202738990948,
          "99.90": 6.246202738990948,
          "99.99": 6.246202738990948,
          "100.00": 6.246202738990948
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            6.246202738990948,
            6.230807920362838,
            6.2335594663545875
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day1Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 2.7050884068694856,
        "scoreError": 0.0050280227842334855,
        "scoreConfidence": [
          2.700060384085252,
          2.710116429653719
        ],
        "scorePercentiles": {
          "0.00": 2.699959528623638,
          "25.00": 2.699959528623638,
          "50.00": 2.707536564503936,
          "75.00": 2.7077691274808835,
          "90.00": 2.7077691274808835,
          "99.00": 2.7077691274808835,
          "99.90": 2.7077691274808835,
          "99.99": 2.7077691274808835,
          "100.00": 2.7077691274808835
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            2.7077691274808835,
            2.707536564503936,
            2.699959528623638
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day2Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 4.9263043139677425,
        "scoreError": 0.004279579634458716,
        "scoreConfidence": [
          4.9220247343332835,
          4.9305838936022015
        ],
        "scorePercentiles": {
          "0.00": 4.922169565449442,
          "25.00": 4.922169565449442,
          "50.00": 4.927154983416835,
          "75.00": 4.9295883930369495,
          "90.00": 4.9295883930369495,
          "99.00": 4.9295883930369495,
          "99.90": 4.9295883930369495,
          "99.99": 4.9295883930369495,
          "100.00": 4.9295883930369495
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            4.9295883930369495,
            4.922169565449442,
            4.927154983416835
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day2Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 4.277323005572754,
        "scoreError": 0.009817791210582663,
        "scoreConfidence": [
          4.2675052143621715,
          4.287140796783336
        ],
        "scorePercentiles": {
          "0.00": 4.267460406971675,
          "25.00": 4.267460406971675,
          "50.00": 4.2807313395890345,
          "75.00": 4.283777270157551,
          "90.00": 4.283777270157551,
          "99.00": 4.283777270157551,
          "99.90": 4.283777270157551,
          "99.99": 4.283777270157551,
          "100.00": 4.283777270157551
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            4.267460406971675,
            4.2807313395890345,
            4.283777270157551
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day3Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 0.5468093866173883,
        "scoreError": 0.00045147828516249453,
        "scoreConfidence": [
          0.5463579083322259,
          0.5472608649025508
        ],
        "scorePercentiles": {
          "0.00": 0.5463559902393502,
          "25.00": 0.5463559902393502,
          "50.00": 0.5469653619622085,
          "75.00": 0.5471068076506065,
          "90.00": 0.5471068076506065,
          "99.00": 0.5471068076506065,
          "99.90": 0.5471068076506065,
          "99.99": 0.5471068076506065,
          "100.00": 0.5471068076506065
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            0.5469653619622085,
            0.5463559902393502,
            0.5471068076506065
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day3Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 1.213268221708039,
        "scoreError": 0.0006474552642410627,
        "scoreConfidence": [
          1.212620766443798,
          1.21391567697228
        ],
        "scorePercentiles": {
          "0.00": 1.2127902829276493,
          "25.00": 1.2127902829276493,
          "50.00": 1.2131121680893258,
          "75.00": 1.2139022141071425,
          "90.00": 1.2139022141071425,
          "99.00": 1.2139022141071425,
          "99.90": 1.2139022141071425,
          "99.99": 1.2139022141071425,
          "100.00": 1.2139022141071425
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            1.2139022141071425,
            1.2127902829276493,
            1.2131121680893258
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day4Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 0.4927959774069752,
        "scoreError": 0.001631986349323383,
        "scoreConfidence": [
          0.49116399105765185,
          0.4944279637562986
        ],
        "scorePercentiles": {
          "0.00": 0.4911561091470324,
          "25.00": 0.4911561091470324,
          "50.00": 0.49336486844494554,
          "75.00": 0.4938669546289478,
          "90.00": 0.4938669546289478,
          "99.00": 0.4938669546289478,
          "99.90": 0.4938669546289478,
          "99.99": 0.4938669546289478,
          "100.00": 0.4938669546289478
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            0.4911561091470324,
            0.49336486844494554,
            0.4938669546289478
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day4Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 0.49454488183692763,
        "scoreError": 0.0003686916320901368,
        "scoreConfidence": [
          0.4941761902048375,
          0.49491357346901776
        ],
        "scorePercentiles": {
          "0.00": 0.4942545544074425,
          "25.00": 0.4942545544074425,
          "50.00": 0.4944828347431443,
          "75.00": 0.4948972563601961,
          "90.00": 0.4948972563601961,
          "99.00": 0.4948972563601961,
          "99.90": 0.4948972563601961,
          "99.99": 0.4948972563601961,
          "100.00": 0.4948972563601961
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            0.4942545544074425,
            0.4948972563601961,
            0.4944828347431443
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day5Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 0.09687542083968219,
        "scoreError": 0.0025361347313184947,
        "scoreConfidence": [
          0.09433928610836369,
          0.09941155557100069
        ],
        "scorePercentiles": {
          "0.00": 0.09537531390249718,
          "25.00": 0.09537531390249718,
          "50.00": 0.09579923489392297,
          "75.00": 0.0994517137226264,
          "90.00": 0.0994517137226264,
          "99.00": 0.0994517137226264,
          "99.90": 0.0994517137226264,
          "99.99": 0.0994517137226264,
          "100.00": 0.0994517137226264
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            0.09579923489392297,
            0.09537531390249718,
            0.0994517137226264
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day5Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 0.04281522490747527,
        "scoreError": 0.004226794238092891,
        "scoreConfidence": [
          0.038588430669382376,
          0.04704201914556816
        ],
        "scorePercentiles": {
          "0.00": 0.038503228230607214,
          "25.00": 0.038503228230607214,
          "50.00": 0.044888468785382774,
          "75.00": 0.04505397770643581,
          "90.00": 0.04505397770643581,
          "99.00": 0.04505397770643581,
          "99.90": 0.04505397770643581,
          "99.99": 0.04505397770643581,
          "100.00": 0.04505397770643581
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            0.038503228230607214,
            0.04505397770643581,
            0.044888468785382774
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day6Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 14.915466887542967,
        "scoreError": 0.038939497264668506,
        "scoreConfidence": [
          14.8765273902783,
          14.954406384807635
        ],
        "scorePercentiles": {
          "0.00": 14.876282117727778,
          "25.00": 14.876282117727778,
          "50.00": 14.929356710860432,
          "75.00": 14.940761834040696,
          "90.00": 14.940761834040696,
          "99.00": 14.940761834040696,
          "99.90": 14.940761834040696,
          "99.99": 14.940761834040696,
          "100.00": 14.940761834040696
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            14.876282117727778,
            14.940761834040696,
            14.929356710860432
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day6Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 14.757636052989577,
        "scoreError": 0.01299864572524629,
        "scoreConfidence": [
          14.74463740726433,
          14.770634698714824
        ],
        "scorePercentiles": {
          "0.00": 14.749699119475034,
          "25.00": 14.749699119475034,
          "50.00": 14.752401119350012,
          "75.00": 14.770807920143687,
          "90.00": 14.770807920143687,
          "99.00": 14.770807920143687,
          "99.90": 14.770807920143687,
          "99.99": 14.770807920143687,
          "100.00": 14.770807920143687
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            14.749699119475034,
            14.752401119350012,
            14.770807920143687
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day7Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 2.1658236003779394,
        "scoreError": 0.004273116085803377,
        "scoreConfidence": [
          2.1615504842921363,
          2.1700967164637426
        ],
        "scorePercentiles": {
          "0.00": 2.1621814585515677,
          "25.00": 2.1621814585515677,
          "50.00": 2.165568518200817,
          "75.00": 2.1697208243814345,
          "90.00": 2.1697208243814345,
          "99.00": 2.1697208243814345,
          "99.90": 2.1697208243814345,
          "99.99": 2.1697208243814345,
          "100.00": 2.1697208243814345
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            2.165568518200817,
            2.1697208243814345,
            2.1621814585515677
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day7Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 3.937253458868566,
        "scoreError": 0.20056875849116473,
        "scoreConfidence": [
          3.7366847003774013,
          4.137822217359731
        ],
        "scorePercentiles": {
          "0.00": 3.834537999322631,
          "25.00": 3.834537999322631,
          "50.00": 3.835307402034531,
          "75.00": 4.141914975248537,
          "90.00": 4.141914975248537,
          "99.00": 4.141914975248537,
          "99.90": 4.141914975248537,
          "99.99": 4.141914975248537,
          "100.00": 4.141914975248537
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            4.141914975248537,
            3.834537999322631,
            3.835307402034531
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day8Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 3.923908062944051,
        "scoreError": 0.011221889330843806,
        "scoreConfidence": [
          3.912686173613207,
          3.935129952274895
        ],
        "scorePercentiles": {
          "0.00": 3.9170076364094033,
          "25.00": 3.9170076364094033,
          "50.00": 3.919444329861773,
          "75.00": 3.9352722225609758,
          "90.00": 3.9352722225609758,
          "99.00": 3.9352722225609758,
          "99.90": 3.9352722225609758,
          "99.99": 3.9352722225609758,
          "100.00": 3.9352722225609758
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            3.9170076364094033,
            3.9352722225609758,
            3.919444329861773
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day8Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 0.14677872799810746,
        "scoreError": 0.00012380354352793722,
        "scoreConfidence": [
          0.1466549244545795,
          0.1469025315416354
        ],
        "scorePercentiles": {
          "0.00": 0.14665409256472312,
          "25.00": 0.14665409256472312,
          "50.00": 0.14682318553600093,
          "75.00": 0.14685890589359835,
          "90.00": 0.14685890589359835,
          "99.00": 0.14685890589359835,
          "99.90": 0.14685890589359835,
          "99.99": 0.14685890589359835,
          "100.00": 0.14685890589359835
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            0.14685890589359835,
            0.14665409256472312,
            0.14682318553600093
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day9Bench.part1",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 0.7542511534379641,
        "scoreError": 0.003932253201923779,
        "scoreConfidence": [
          0.7503189002360403,
          0.7581834066398879
        ],
        "scorePercentiles": {
          "0.00": 0.7519880653513511,
          "25.00": 0.7519880653513511,
          "50.00": 0.7525132095327759,
          "75.00": 0.7582521854297655,
          "90.00": 0.7582521854297655,
          "99.00": 0.7582521854297655,
          "99.90": 0.7582521854297655,
          "99.99": 0.7582521854297655,
          "100.00": 0.7582521854297655
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            0.7582521854297655,
            0.7519880653513511,
            0.7525132095327759
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "benchmark": "com.github.ephemient.aoc2021.Day9Bench.part2",
      "mode": "thrpt",
      "warmupIterations": 1,
      "warmupTime": "1 sec",
      "measurementIterations": 3,
      "measurementTime": "1 sec",
      "params": {},
      "nativeFork": "perBenchmark",
      "nativeGCAfterIteration": false,
      "primaryMetric": {
        "score": 0.12484904971726309,
        "scoreError": 8.987084105895372e-05,
        "scoreConfidence": [
          0.12475917887620414,
          0.12493892055832204
        ],
        "scorePercentiles": {
          "0.00": 0.12479007750766621,
          "25.00": 0.12479007750766621,
          "50.00": 0.12481771595797955,
          "75.00": 0.12493935568614352,
          "90.00": 0.12493935568614352,
          "99.00": 0.12493935568614352,
          "99.90": 0.12493935568614352,
          "99.99": 0.12493935568614352,
          "100.00": 0.12493935568614352
        },
        "scoreUnit": "ops/ms",
        "rawData": [
          [
            0.12479007750766621,
            0.12493935568614352,
            0.12481771595797955
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ],
  "jvmBench": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day1Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 24503.62462462826,
        "scoreError": 5873.345322705537,
        "scoreConfidence": [
          18630.279301922725,
          30376.969947333797
        ],
        "scorePercentiles": {
          "0.0": 21782.051919068042,
          "50.0": 25118.029293728705,
          "90.0": 25344.43334616286,
          "95.0": 25344.43334616286,
          "99.0": 25344.43334616286,
          "99.9": 25344.43334616286,
          "99.99": 25344.43334616286,
          "99.999": 25344.43334616286,
          "99.9999": 25344.43334616286,
          "100.0": 25344.43334616286
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            21782.051919068042,
            25118.029293728705,
            25056.853197069056,
            25216.755367112637,
            25344.43334616286
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day1Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 14888.423860204837,
        "scoreError": 490.4608405816032,
        "scoreConfidence": [
          14397.963019623234,
          15378.88470078644
        ],
        "scorePercentiles": {
          "0.0": 14731.905801319155,
          "50.0": 14924.680627454933,
          "90.0": 15038.851430445402,
          "95.0": 15038.851430445402,
          "99.0": 15038.851430445402,
          "99.9": 15038.851430445402,
          "99.99": 15038.851430445402,
          "99.999": 15038.851430445402,
          "99.9999": 15038.851430445402,
          "100.0": 15038.851430445402
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            14924.680627454933,
            15038.851430445402,
            14962.777010145157,
            14783.90443165954,
            14731.905801319155
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day2Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 13942.777796735778,
        "scoreError": 374.45113673071114,
        "scoreConfidence": [
          13568.326660005067,
          14317.22893346649
        ],
        "scorePercentiles": {
          "0.0": 13808.342224083397,
          "50.0": 13959.662510351292,
          "90.0": 14049.131613757547,
          "95.0": 14049.131613757547,
          "99.0": 14049.131613757547,
          "99.9": 14049.131613757547,
          "99.99": 14049.131613757547,
          "99.999": 14049.131613757547,
          "99.9999": 14049.131613757547,
          "100.0": 14049.131613757547
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            13808.342224083397,
            14011.990648061634,
            14049.131613757547,
            13884.761987425007,
            13959.662510351292
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day2Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 13415.047096705104,
        "scoreError": 212.95619431234422,
        "scoreConfidence": [
          13202.09090239276,
          13628.003291017449
        ],
        "scorePercentiles": {
          "0.0": 13332.239996514218,
          "50.0": 13432.222413339277,
          "90.0": 13475.378294743481,
          "95.0": 13475.378294743481,
          "99.0": 13475.378294743481,
          "99.9": 13475.378294743481,
          "99.99": 13475.378294743481,
          "99.999": 13475.378294743481,
          "99.9999": 13475.378294743481,
          "100.0": 13475.378294743481
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            13332.239996514218,
            13390.974349518649,
            13432.222413339277,
            13444.420429409894,
            13475.378294743481
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day3Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 5069.428514201414,
        "scoreError": 59.45782148887756,
        "scoreConfidence": [
          5009.970692712536,
          5128.886335690292
        ],
        "scorePercentiles": {
          "0.0": 5050.570756275363,
          "50.0": 5077.655360393828,
          "90.0": 5083.52599097071,
          "95.0": 5083.52599097071,
          "99.0": 5083.52599097071,
          "99.9": 5083.52599097071,
          "99.99": 5083.52599097071,
          "99.999": 5083.52599097071,
          "99.9999": 5083.52599097071,
          "100.0": 5083.52599097071
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            5077.655360393828,
            5054.934835510294,
            5050.570756275363,
            5080.455627856877,
            5083.52599097071
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day3Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 9364.031788698212,
        "scoreError": 153.4015010382297,
        "scoreConfidence": [
          9210.630287659982,
          9517.433289736442
        ],
        "scorePercentiles": {
          "0.0": 9293.349886517284,
          "50.0": 9382.910763019212,
          "90.0": 9385.621571302308,
          "95.0": 9385.621571302308,
          "99.0": 9385.621571302308,
          "99.9": 9385.621571302308,
          "99.99": 9385.621571302308,
          "99.999": 9385.621571302308,
          "99.9999": 9385.621571302308,
          "100.0": 9385.621571302308
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            9293.349886517284,
            9385.621571302308,
            9382.910763019212,
            9385.194136664544,
            9373.082585987715
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day4Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2343.132187772891,
        "scoreError": 837.5535462647376,
        "scoreConfidence": [
          1505.5786415081534,
          3180.6857340376287
        ],
        "scorePercentiles": {
          "0.0": 1954.6146507750625,
          "50.0": 2437.6269335008974,
          "90.0": 2451.9232626792063,
          "95.0": 2451.9232626792063,
          "99.0": 2451.9232626792063,
          "99.9": 2451.9232626792063,
          "99.99": 2451.9232626792063,
          "99.999": 2451.9232626792063,
          "99.9999": 2451.9232626792063,
          "100.0": 2451.9232626792063
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1954.6146507750625,
            2437.6269335008974,
            2451.9232626792063,
            2422.0300302575424,
            2449.4660616517463
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day4Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2408.466383609152,
        "scoreError": 109.84569357038698,
        "scoreConfidence": [
          2298.620690038765,
          2518.3120771795393
        ],
        "scorePercentiles": {
          "0.0": 2358.011575910715,
          "50.0": 2420.3543777308037,
          "90.0": 2425.63677059615,
          "95.0": 2425.63677059615,
          "99.0": 2425.63677059615,
          "99.9": 2425.63677059615,
          "99.99": 2425.63677059615,
          "99.999": 2425.63677059615,
          "99.9999": 2425.63677059615,
          "100.0": 2425.63677059615
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2358.011575910715,
            2414.456900392605,
            2420.3543777308037,
            2423.8722934154885,
            2425.63677059615
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day5Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 558.9480540226316,
        "scoreError": 11.455208835528397,
        "scoreConfidence": [
          547.4928451871032,
          570.40326285816
        ],
        "scorePercentiles": {
          "0.0": 553.731201996665,
          "50.0": 560.196865920417,
          "90.0": 561.0393889193317,
          "95.0": 561.0393889193317,
          "99.0": 561.0393889193317,
          "99.9": 561.0393889193317,
          "99.99": 561.0393889193317,
          "99.999": 561.0393889193317,
          "99.9999": 561.0393889193317,
          "100.0": 561.0393889193317
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            553.731201996665,
            559.3914787531091,
            560.196865920417,
            561.0393889193317,
            560.3813345236352
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day5Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 190.73363040230672,
        "scoreError": 6.653119134507692,
        "scoreConfidence": [
          184.080511267799,
          197.38674953681442
        ],
        "scorePercentiles": {
          "0.0": 187.69234909309952,
          "50.0": 191.40222463037458,
          "90.0": 191.9670977992727,
          "95.0": 191.9670977992727,
          "99.0": 191.9670977992727,
          "99.9": 191.9670977992727,
          "99.99": 191.9670977992727,
          "99.999": 191.9670977992727,
          "99.9999": 191.9670977992727,
          "100.0": 191.9670977992727
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            187.69234909309952,
            191.11046525506333,
            191.49601523372345,
            191.9670977992727,
            191.40222463037458
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day6Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 72728.06055996905,
        "scoreError": 759.1783062458886,
        "scoreConfidence": [
          71968.88225372316,
          73487.23886621493
        ],
        "scorePercentiles": {
          "0.0": 72527.12260821801,
          "50.0": 72724.52349127636,
          "90.0": 73037.48618059787,
          "95.0": 73037.48618059787,
          "99.0": 73037.48618059787,
          "99.9": 73037.48618059787,
          "99.99": 73037.48618059787,
          "99.999": 73037.48618059787,
          "99.9999": 73037.48618059787,
          "100.0": 73037.48618059787
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            72527.12260821801,
            72758.7782916295,
            72724.52349127636,
            72592.3922281235,
            73037.48618059787
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day6Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 70097.12664567746,
        "scoreError": 424.847670193754,
        "scoreConfidence": [
          69672.27897548371,
          70521.97431587121
        ],
        "scorePercentiles": {
          "0.0": 69954.74280673596,
          "50.0": 70058.74687305739,
          "90.0": 70213.70686970772,
          "95.0": 70213.70686970772,
          "99.0": 70213.70686970772,
          "99.9": 70213.70686970772,
          "99.99": 70213.70686970772,
          "99.999": 70213.70686970772,
          "99.9999": 70213.70686970772,
          "100.0": 70213.70686970772
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            70204.36943029503,
            70213.70686970772,
            70054.06724859116,
            70058.74687305739,
            69954.74280673596
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day7Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 5796.0909840381055,
        "scoreError": 349.9871040086355,
        "scoreConfidence": [
          5446.10388002947,
          6146.078088046741
        ],
        "scorePercentiles": {
          "0.0": 5659.469611503414,
          "50.0": 5852.90589874163,
          "90.0": 5866.036016114868,
          "95.0": 5866.036016114868,
          "99.0": 5866.036016114868,
          "99.9": 5866.036016114868,
          "99.99": 5866.036016114868,
          "99.999": 5866.036016114868,
          "99.9999": 5866.036016114868,
          "100.0": 5866.036016114868
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            5659.469611503414,
            5745.298742353505,
            5856.7446514771145,
            5852.90589874163,
            5866.036016114868
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day7Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 17353.261286176792,
        "scoreError": 213.34908870222455,
        "scoreConfidence": [
          17139.91219747457,
          17566.610374879016
        ],
        "scorePercentiles": {
          "0.0": 17265.9123206459,
          "50.0": 17366.31821283272,
          "90.0": 17412.024242856533,
          "95.0": 17412.024242856533,
          "99.0": 17412.024242856533,
          "99.9": 17412.024242856533,
          "99.99": 17412.024242856533,
          "99.999": 17412.024242856533,
          "99.9999": 17412.024242856533,
          "100.0": 17412.024242856533
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            17265.9123206459,
            17412.024242856533,
            17382.301973286823,
            17339.749681261997,
            17366.31821283272
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day8Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 33914.52465145074,
        "scoreError": 643.4499983696742,
        "scoreConfidence": [
          33271.074653081065,
          34557.97464982041
        ],
        "scorePercentiles": {
          "0.0": 33654.826150276596,
          "50.0": 33939.060087520666,
          "90.0": 34068.86195672581,
          "95.0": 34068.86195672581,
          "99.0": 34068.86195672581,
          "99.9": 34068.86195672581,
          "99.99": 34068.86195672581,
          "99.999": 34068.86195672581,
          "99.9999": 34068.86195672581,
          "100.0": 34068.86195672581
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            33654.826150276596,
            34068.86195672581,
            33863.94164235851,
            33939.060087520666,
            34045.933420372116
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day8Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 3012.995057405372,
        "scoreError": 85.1194759856041,
        "scoreConfidence": [
          2927.875581419768,
          3098.114533390976
        ],
        "scorePercentiles": {
          "0.0": 2975.8698734871327,
          "50.0": 3022.802300512675,
          "90.0": 3029.413569150697,
          "95.0": 3029.413569150697,
          "99.0": 3029.413569150697,
          "99.9": 3029.413569150697,
          "99.99": 3029.413569150697,
          "99.999": 3029.413569150697,
          "99.9999": 3029.413569150697,
          "100.0": 3029.413569150697
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2975.8698734871327,
            3009.7516122165334,
            3029.413569150697,
            3027.137931659822,
            3022.802300512675
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day9Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 10843.673180959042,
        "scoreError": 109.78434416953117,
        "scoreConfidence": [
          10733.88883678951,
          10953.457525128573
        ],
        "scorePercentiles": {
          "0.0": 10817.639105908966,
          "50.0": 10827.627006437642,
          "90.0": 10881.677469169368,
          "95.0": 10881.677469169368,
          "99.0": 10881.677469169368,
          "99.9": 10881.677469169368,
          "99.99": 10881.677469169368,
          "99.999": 10881.677469169368,
          "99.9999": 10881.677469169368,
          "100.0": 10881.677469169368
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            10817.639105908966,
            10827.627006437642,
            10881.677469169368,
            10866.490264175147,
            10824.932059104089
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day9Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 777.7689706152239,
        "scoreError": 22.365500381099007,
        "scoreConfidence": [
          755.4034702341249,
          800.1344709963229
        ],
        "scorePercentiles": {
          "0.0": 767.7133492768528,
          "50.0": 779.1286645744877,
          "90.0": 782.0259038420189,
          "95.0": 782.0259038420189,
          "99.0": 782.0259038420189,
          "99.9": 782.0259038420189,
          "99.99": 782.0259038420189,
          "99.999": 782.0259038420189,
          "99.9999": 782.0259038420189,
          "100.0": 782.0259038420189
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            767.7133492768528,
            779.1286645744877,
            778.5733807160367,
            781.4035546667229,
            782.0259038420189
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ]
};
