// provided.js - generated by ephemient/aoc2021/Kotlin benchmarks, 2021-12-22 22:01:52.202628236

var providedBenchmarks = ["jvmBench"];

var providedBenchmarkStore = {
  "jvmBench": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day10Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 8718.027126888672,
        "scoreError": 974.1883369329573,
        "scoreConfidence": [
          7743.838789955715,
          9692.215463821629
        ],
        "scorePercentiles": {
          "0.0": 8289.015642811173,
          "50.0": 8846.317024237924,
          "90.0": 8898.05314276018,
          "95.0": 8898.05314276018,
          "99.0": 8898.05314276018,
          "99.9": 8898.05314276018,
          "99.99": 8898.05314276018,
          "99.999": 8898.05314276018,
          "99.9999": 8898.05314276018,
          "100.0": 8898.05314276018
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            8867.315493083122,
            8846.317024237924,
            8898.05314276018,
            8689.434331550963,
            8289.015642811173
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day10Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 6658.375160684847,
        "scoreError": 386.56697025695433,
        "scoreConfidence": [
          6271.808190427893,
          7044.942130941801
        ],
        "scorePercentiles": {
          "0.0": 6516.49797328315,
          "50.0": 6666.257466963166,
          "90.0": 6754.869944032713,
          "95.0": 6754.869944032713,
          "99.0": 6754.869944032713,
          "99.9": 6754.869944032713,
          "99.99": 6754.869944032713,
          "99.999": 6754.869944032713,
          "99.9999": 6754.869944032713,
          "100.0": 6754.869944032713
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            6748.213681901883,
            6606.0367372433275,
            6666.257466963166,
            6516.49797328315,
            6754.869944032713
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day11Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2778.8169461206635,
        "scoreError": 200.46003247008312,
        "scoreConfidence": [
          2578.3569136505803,
          2979.2769785907467
        ],
        "scorePercentiles": {
          "0.0": 2714.5144494153637,
          "50.0": 2783.803434332533,
          "90.0": 2846.7198354779234,
          "95.0": 2846.7198354779234,
          "99.0": 2846.7198354779234,
          "99.9": 2846.7198354779234,
          "99.99": 2846.7198354779234,
          "99.999": 2846.7198354779234,
          "99.9999": 2846.7198354779234,
          "100.0": 2846.7198354779234
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2846.7198354779234,
            2742.6397877972418,
            2714.5144494153637,
            2783.803434332533,
            2806.407223580257
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day11Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2972.326547917734,
        "scoreError": 150.91436361914452,
        "scoreConfidence": [
          2821.4121842985896,
          3123.2409115368782
        ],
        "scorePercentiles": {
          "0.0": 2921.108319463399,
          "50.0": 2988.7419484920133,
          "90.0": 3013.48111471382,
          "95.0": 3013.48111471382,
          "99.0": 3013.48111471382,
          "99.9": 3013.48111471382,
          "99.99": 3013.48111471382,
          "99.999": 3013.48111471382,
          "99.9999": 3013.48111471382,
          "100.0": 3013.48111471382
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2988.7419484920133,
            2941.4252160685746,
            3013.48111471382,
            2921.108319463399,
            2996.8761408508644
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day12Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1228.507937903113,
        "scoreError": 79.69144699992366,
        "scoreConfidence": [
          1148.8164909031893,
          1308.1993849030368
        ],
        "scorePercentiles": {
          "0.0": 1200.9161949241268,
          "50.0": 1239.5366748258534,
          "90.0": 1247.457146568442,
          "95.0": 1247.457146568442,
          "99.0": 1247.457146568442,
          "99.9": 1247.457146568442,
          "99.99": 1247.457146568442,
          "99.999": 1247.457146568442,
          "99.9999": 1247.457146568442,
          "100.0": 1247.457146568442
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1212.0116142246927,
            1239.5366748258534,
            1247.457146568442,
            1242.6180589724497,
            1200.9161949241268
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day12Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 50.75263918311199,
        "scoreError": 4.005533409547737,
        "scoreConfidence": [
          46.74710577356425,
          54.758172592659726
        ],
        "scorePercentiles": {
          "0.0": 49.001642735971245,
          "50.0": 50.96208302927795,
          "90.0": 51.75684190563891,
          "95.0": 51.75684190563891,
          "99.0": 51.75684190563891,
          "99.9": 51.75684190563891,
          "99.99": 51.75684190563891,
          "99.999": 51.75684190563891,
          "99.9999": 51.75684190563891,
          "100.0": 51.75684190563891
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            49.001642735971245,
            51.75684190563891,
            50.96208302927795,
            50.84018489558443,
            51.202443349087424
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day13Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 6001.21975305713,
        "scoreError": 614.9417803327626,
        "scoreConfidence": [
          5386.277972724368,
          6616.161533389893
        ],
        "scorePercentiles": {
          "0.0": 5810.739479156727,
          "50.0": 5985.806795261236,
          "90.0": 6242.422079438698,
          "95.0": 6242.422079438698,
          "99.0": 6242.422079438698,
          "99.9": 6242.422079438698,
          "99.99": 6242.422079438698,
          "99.999": 6242.422079438698,
          "99.9999": 6242.422079438698,
          "100.0": 6242.422079438698
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            5985.806795261236,
            5925.720030193792,
            6041.410381235192,
            5810.739479156727,
            6242.422079438698
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day13Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4144.842656239741,
        "scoreError": 140.47490799949423,
        "scoreConfidence": [
          4004.3677482402463,
          4285.317564239235
        ],
        "scorePercentiles": {
          "0.0": 4089.3151018045037,
          "50.0": 4140.9978785134,
          "90.0": 4181.007135211559,
          "95.0": 4181.007135211559,
          "99.0": 4181.007135211559,
          "99.9": 4181.007135211559,
          "99.99": 4181.007135211559,
          "99.999": 4181.007135211559,
          "99.9999": 4181.007135211559,
          "100.0": 4181.007135211559
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            4138.444399179767,
            4181.007135211559,
            4089.3151018045037,
            4140.9978785134,
            4174.448766489475
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day14Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 41491.34448652658,
        "scoreError": 7215.1723002182935,
        "scoreConfidence": [
          34276.172186308286,
          48706.51678674487
        ],
        "scorePercentiles": {
          "0.0": 39390.92993451539,
          "50.0": 41377.0280529538,
          "90.0": 43588.503915169495,
          "95.0": 43588.503915169495,
          "99.0": 43588.503915169495,
          "99.9": 43588.503915169495,
          "99.99": 43588.503915169495,
          "99.999": 43588.503915169495,
          "99.9999": 43588.503915169495,
          "100.0": 43588.503915169495
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            41377.0280529538,
            39390.92993451539,
            39935.49912460858,
            43164.76140538559,
            43588.503915169495
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day14Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 19295.35192107257,
        "scoreError": 1275.2748329183048,
        "scoreConfidence": [
          18020.077088154267,
          20570.626753990877
        ],
        "scorePercentiles": {
          "0.0": 18913.655434136967,
          "50.0": 19276.286991465335,
          "90.0": 19631.651883015395,
          "95.0": 19631.651883015395,
          "99.0": 19631.651883015395,
          "99.9": 19631.651883015395,
          "99.99": 19631.651883015395,
          "99.999": 19631.651883015395,
          "99.9999": 19631.651883015395,
          "100.0": 19631.651883015395
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            19625.49418535926,
            19631.651883015395,
            19276.286991465335,
            19029.67111138591,
            18913.655434136967
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day15Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 424.33850085659844,
        "scoreError": 57.03566410010228,
        "scoreConfidence": [
          367.30283675649616,
          481.3741649567007
        ],
        "scorePercentiles": {
          "0.0": 403.00341607641195,
          "50.0": 422.07641660594703,
          "90.0": 441.42610192488746,
          "95.0": 441.42610192488746,
          "99.0": 441.42610192488746,
          "99.9": 441.42610192488746,
          "99.99": 441.42610192488746,
          "99.999": 441.42610192488746,
          "99.9999": 441.42610192488746,
          "100.0": 441.42610192488746
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            403.00341607641195,
            422.07641660594703,
            434.80795358825117,
            420.37861608749444,
            441.42610192488746
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day15Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 12.412867253927422,
        "scoreError": 0.8968553785563329,
        "scoreConfidence": [
          11.516011875371088,
          13.309722632483755
        ],
        "scorePercentiles": {
          "0.0": 12.108451969213565,
          "50.0": 12.388515097475958,
          "90.0": 12.680782762518806,
          "95.0": 12.680782762518806,
          "99.0": 12.680782762518806,
          "99.9": 12.680782762518806,
          "99.99": 12.680782762518806,
          "99.999": 12.680782762518806,
          "99.9999": 12.680782762518806,
          "100.0": 12.680782762518806
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            12.108451969213565,
            12.60156087430777,
            12.285025566121005,
            12.680782762518806,
            12.388515097475958
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day16Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 7780.296287235273,
        "scoreError": 566.9075029852884,
        "scoreConfidence": [
          7213.388784249984,
          8347.203790220561
        ],
        "scorePercentiles": {
          "0.0": 7599.195153859919,
          "50.0": 7802.440823847969,
          "90.0": 7956.728561701877,
          "95.0": 7956.728561701877,
          "99.0": 7956.728561701877,
          "99.9": 7956.728561701877,
          "99.99": 7956.728561701877,
          "99.999": 7956.728561701877,
          "99.9999": 7956.728561701877,
          "100.0": 7956.728561701877
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            7599.195153859919,
            7802.440823847969,
            7666.366555383058,
            7956.728561701877,
            7876.750341383545
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day16Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 7256.673643890297,
        "scoreError": 369.9049418757741,
        "scoreConfidence": [
          6886.768702014523,
          7626.578585766071
        ],
        "scorePercentiles": {
          "0.0": 7140.587615489619,
          "50.0": 7307.675699931849,
          "90.0": 7337.139106555463,
          "95.0": 7337.139106555463,
          "99.0": 7337.139106555463,
          "99.9": 7337.139106555463,
          "99.99": 7337.139106555463,
          "99.999": 7337.139106555463,
          "99.9999": 7337.139106555463,
          "100.0": 7337.139106555463
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            7140.587615489619,
            7164.595858944487,
            7337.139106555463,
            7307.675699931849,
            7333.369938530063
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day17Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2204.8057204919287,
        "scoreError": 203.85758812543347,
        "scoreConfidence": [
          2000.9481323664952,
          2408.663308617362
        ],
        "scorePercentiles": {
          "0.0": 2150.9417437080774,
          "50.0": 2199.978591739449,
          "90.0": 2288.789887961849,
          "95.0": 2288.789887961849,
          "99.0": 2288.789887961849,
          "99.9": 2288.789887961849,
          "99.99": 2288.789887961849,
          "99.999": 2288.789887961849,
          "99.9999": 2288.789887961849,
          "100.0": 2288.789887961849
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2170.7906361955393,
            2199.978591739449,
            2288.789887961849,
            2213.527742854728,
            2150.9417437080774
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day18Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 143.49993100902938,
        "scoreError": 10.673921511015166,
        "scoreConfidence": [
          132.82600949801423,
          154.17385252004453
        ],
        "scorePercentiles": {
          "0.0": 139.02804851752376,
          "50.0": 143.52251065363112,
          "90.0": 145.87500293312954,
          "95.0": 145.87500293312954,
          "99.0": 145.87500293312954,
          "99.9": 145.87500293312954,
          "99.99": 145.87500293312954,
          "99.999": 145.87500293312954,
          "99.9999": 145.87500293312954,
          "100.0": 145.87500293312954
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            139.02804851752376,
            143.52251065363112,
            143.3235506782162,
            145.75054226264632,
            145.87500293312954
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day18Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 7.94621145890837,
        "scoreError": 0.5880480995841141,
        "scoreConfidence": [
          7.358163359324256,
          8.534259558492485
        ],
        "scorePercentiles": {
          "0.0": 7.676692892984411,
          "50.0": 7.998885261129768,
          "90.0": 8.045545993202643,
          "95.0": 8.045545993202643,
          "99.0": 8.045545993202643,
          "99.9": 8.045545993202643,
          "99.99": 8.045545993202643,
          "99.999": 8.045545993202643,
          "99.9999": 8.045545993202643,
          "100.0": 8.045545993202643
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            7.676692892984411,
            7.981513712792281,
            8.045545993202643,
            7.998885261129768,
            8.028419434432747
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day19Bench.solve",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 0.5857286536072924,
        "scoreError": 0.15856324435921637,
        "scoreConfidence": [
          0.42716540924807606,
          0.7442918979665087
        ],
        "scorePercentiles": {
          "0.0": 0.5378637771398229,
          "50.0": 0.5880739193697295,
          "90.0": 0.6280493491635132,
          "95.0": 0.6280493491635132,
          "99.0": 0.6280493491635132,
          "99.9": 0.6280493491635132,
          "99.99": 0.6280493491635132,
          "99.999": 0.6280493491635132,
          "99.9999": 0.6280493491635132,
          "100.0": 0.6280493491635132
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            0.5378637771398229,
            0.5506543570271322,
            0.5880739193697295,
            0.6280493491635132,
            0.6240018653362641
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day1Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 20997.20394851897,
        "scoreError": 958.5905170987176,
        "scoreConfidence": [
          20038.613431420254,
          21955.794465617688
        ],
        "scorePercentiles": {
          "0.0": 20630.360408545497,
          "50.0": 21057.684408724705,
          "90.0": 21301.805422656515,
          "95.0": 21301.805422656515,
          "99.0": 21301.805422656515,
          "99.9": 21301.805422656515,
          "99.99": 21301.805422656515,
          "99.999": 21301.805422656515,
          "99.9999": 21301.805422656515,
          "100.0": 21301.805422656515
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            20906.22992706978,
            20630.360408545497,
            21301.805422656515,
            21089.939575598368,
            21057.684408724705
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day1Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 12840.131153996377,
        "scoreError": 743.090979512666,
        "scoreConfidence": [
          12097.04017448371,
          13583.222133509043
        ],
        "scorePercentiles": {
          "0.0": 12618.489478435311,
          "50.0": 12784.50665045247,
          "90.0": 13072.769416420257,
          "95.0": 13072.769416420257,
          "99.0": 13072.769416420257,
          "99.9": 13072.769416420257,
          "99.99": 13072.769416420257,
          "99.999": 13072.769416420257,
          "99.9999": 13072.769416420257,
          "100.0": 13072.769416420257
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            12618.489478435311,
            13072.769416420257,
            12784.50665045247,
            12718.176097856991,
            13006.714126816856
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day20Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1810.1168661143565,
        "scoreError": 78.1659250873721,
        "scoreConfidence": [
          1731.9509410269843,
          1888.2827912017287
        ],
        "scorePercentiles": {
          "0.0": 1782.2226339227548,
          "50.0": 1808.3578754222758,
          "90.0": 1839.083377441798,
          "95.0": 1839.083377441798,
          "99.0": 1839.083377441798,
          "99.9": 1839.083377441798,
          "99.99": 1839.083377441798,
          "99.999": 1839.083377441798,
          "99.9999": 1839.083377441798,
          "100.0": 1839.083377441798
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1814.188000292265,
            1839.083377441798,
            1806.732443492689,
            1808.3578754222758,
            1782.2226339227548
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day20Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 34.78553899883152,
        "scoreError": 2.6926142271544444,
        "scoreConfidence": [
          32.092924771677076,
          37.47815322598596
        ],
        "scorePercentiles": {
          "0.0": 33.99634425265832,
          "50.0": 34.64606045432466,
          "90.0": 35.87788920072151,
          "95.0": 35.87788920072151,
          "99.0": 35.87788920072151,
          "99.9": 35.87788920072151,
          "99.99": 35.87788920072151,
          "99.999": 35.87788920072151,
          "99.9999": 35.87788920072151,
          "100.0": 35.87788920072151
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            33.99634425265832,
            34.472431902759126,
            35.87788920072151,
            34.64606045432466,
            34.934969183694
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day21Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 452170.10630231595,
        "scoreError": 48596.26266990813,
        "scoreConfidence": [
          403573.84363240784,
          500766.36897222407
        ],
        "scorePercentiles": {
          "0.0": 431135.0030000726,
          "50.0": 456209.18613966875,
          "90.0": 461845.2145960764,
          "95.0": 461845.2145960764,
          "99.0": 461845.2145960764,
          "99.9": 461845.2145960764,
          "99.99": 461845.2145960764,
          "99.999": 461845.2145960764,
          "99.9999": 461845.2145960764,
          "100.0": 461845.2145960764
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            431135.0030000726,
            461845.2145960764,
            461210.7142544119,
            450450.41352134995,
            456209.18613966875
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day21Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 12085175.698563447,
        "scoreError": 987916.8004552021,
        "scoreConfidence": [
          11097258.898108246,
          13073092.499018649
        ],
        "scorePercentiles": {
          "0.0": 11785881.048169814,
          "50.0": 12128248.615739513,
          "90.0": 12340701.654383022,
          "95.0": 12340701.654383022,
          "99.0": 12340701.654383022,
          "99.9": 12340701.654383022,
          "99.99": 12340701.654383022,
          "99.999": 12340701.654383022,
          "99.9999": 12340701.654383022,
          "100.0": 12340701.654383022
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            11785881.048169814,
            12128248.615739513,
            12340701.654383022,
            12316351.949782513,
            11854695.224742372
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day22Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1611.1186574779028,
        "scoreError": 512.4319856395256,
        "scoreConfidence": [
          1098.6866718383772,
          2123.5506431174285
        ],
        "scorePercentiles": {
          "0.0": 1380.6090722555384,
          "50.0": 1665.1415787776073,
          "90.0": 1704.251652540202,
          "95.0": 1704.251652540202,
          "99.0": 1704.251652540202,
          "99.9": 1704.251652540202,
          "99.99": 1704.251652540202,
          "99.999": 1704.251652540202,
          "99.9999": 1704.251652540202,
          "100.0": 1704.251652540202
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1380.6090722555384,
            1616.4837050250353,
            1689.1072787911316,
            1665.1415787776073,
            1704.251652540202
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day22Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 27.225963791171743,
        "scoreError": 12.927346452557313,
        "scoreConfidence": [
          14.29861733861443,
          40.15331024372905
        ],
        "scorePercentiles": {
          "0.0": 21.370741009967464,
          "50.0": 28.082486692033957,
          "90.0": 29.726908081073773,
          "95.0": 29.726908081073773,
          "99.0": 29.726908081073773,
          "99.9": 29.726908081073773,
          "99.99": 29.726908081073773,
          "99.999": 29.726908081073773,
          "99.9999": 29.726908081073773,
          "100.0": 29.726908081073773
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            21.370741009967464,
            29.726908081073773,
            28.082486692033957,
            27.886818752618353,
            29.06286442016518
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day2Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 10152.196088360759,
        "scoreError": 1541.371726200627,
        "scoreConfidence": [
          8610.824362160132,
          11693.567814561386
        ],
        "scorePercentiles": {
          "0.0": 9493.40875509348,
          "50.0": 10194.28837026495,
          "90.0": 10479.128756039498,
          "95.0": 10479.128756039498,
          "99.0": 10479.128756039498,
          "99.9": 10479.128756039498,
          "99.99": 10479.128756039498,
          "99.999": 10479.128756039498,
          "99.9999": 10479.128756039498,
          "100.0": 10479.128756039498
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            10194.28837026495,
            9493.40875509348,
            10129.316093720832,
            10479.128756039498,
            10464.838466685029
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day2Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 10328.510760608186,
        "scoreError": 708.6180469154252,
        "scoreConfidence": [
          9619.89271369276,
          11037.128807523612
        ],
        "scorePercentiles": {
          "0.0": 10073.828971992238,
          "50.0": 10367.046917363337,
          "90.0": 10551.808083714574,
          "95.0": 10551.808083714574,
          "99.0": 10551.808083714574,
          "99.9": 10551.808083714574,
          "99.99": 10551.808083714574,
          "99.999": 10551.808083714574,
          "99.9999": 10551.808083714574,
          "100.0": 10551.808083714574
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            10422.983236539081,
            10226.886593431695,
            10367.046917363337,
            10551.808083714574,
            10073.828971992238
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day3Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4367.501727035025,
        "scoreError": 246.81601976336975,
        "scoreConfidence": [
          4120.685707271656,
          4614.317746798395
        ],
        "scorePercentiles": {
          "0.0": 4297.761605418573,
          "50.0": 4353.727308617777,
          "90.0": 4469.034402323098,
          "95.0": 4469.034402323098,
          "99.0": 4469.034402323098,
          "99.9": 4469.034402323098,
          "99.99": 4469.034402323098,
          "99.999": 4469.034402323098,
          "99.9999": 4469.034402323098,
          "100.0": 4469.034402323098
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            4353.727308617777,
            4337.170789328301,
            4379.814529487375,
            4297.761605418573,
            4469.034402323098
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day3Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 7809.603190742229,
        "scoreError": 157.90205548046947,
        "scoreConfidence": [
          7651.70113526176,
          7967.505246222699
        ],
        "scorePercentiles": {
          "0.0": 7760.516281944506,
          "50.0": 7799.277420907867,
          "90.0": 7860.6962956586685,
          "95.0": 7860.6962956586685,
          "99.0": 7860.6962956586685,
          "99.9": 7860.6962956586685,
          "99.99": 7860.6962956586685,
          "99.999": 7860.6962956586685,
          "99.9999": 7860.6962956586685,
          "100.0": 7860.6962956586685
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            7760.516281944506,
            7860.6962956586685,
            7785.790435052733,
            7799.277420907867,
            7841.7355201473765
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day4Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1557.5813706423164,
        "scoreError": 2182.6370472509457,
        "scoreConfidence": [
          -625.0556766086293,
          3740.218417893262
        ],
        "scorePercentiles": {
          "0.0": 742.7487554741803,
          "50.0": 1940.1209040566794,
          "90.0": 1980.3129436788988,
          "95.0": 1980.3129436788988,
          "99.0": 1980.3129436788988,
          "99.9": 1980.3129436788988,
          "99.99": 1980.3129436788988,
          "99.999": 1980.3129436788988,
          "99.9999": 1980.3129436788988,
          "100.0": 1980.3129436788988
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            742.7487554741803,
            1177.5758207033211,
            1947.1484292985022,
            1940.1209040566794,
            1980.3129436788988
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day4Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1851.292034553658,
        "scoreError": 1130.2728925201875,
        "scoreConfidence": [
          721.0191420334704,
          2981.5649270738454
        ],
        "scorePercentiles": {
          "0.0": 1326.62964612832,
          "50.0": 1977.0962046371499,
          "90.0": 1999.9243946622896,
          "95.0": 1999.9243946622896,
          "99.0": 1999.9243946622896,
          "99.9": 1999.9243946622896,
          "99.99": 1999.9243946622896,
          "99.999": 1999.9243946622896,
          "99.9999": 1999.9243946622896,
          "100.0": 1999.9243946622896
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1326.62964612832,
            1968.0375547027702,
            1999.9243946622896,
            1984.772372637759,
            1977.0962046371499
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day5Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 505.22810166451546,
        "scoreError": 31.119735262440308,
        "scoreConfidence": [
          474.10836640207515,
          536.3478369269558
        ],
        "scorePercentiles": {
          "0.0": 494.9870830531208,
          "50.0": 505.86316553131326,
          "90.0": 514.3573526651478,
          "95.0": 514.3573526651478,
          "99.0": 514.3573526651478,
          "99.9": 514.3573526651478,
          "99.99": 514.3573526651478,
          "99.999": 514.3573526651478,
          "99.9999": 514.3573526651478,
          "100.0": 514.3573526651478
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            494.9870830531208,
            499.4449648128236,
            505.86316553131326,
            511.48794226017213,
            514.3573526651478
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day5Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 172.59739671810343,
        "scoreError": 11.478434612723152,
        "scoreConfidence": [
          161.11896210538026,
          184.0758313308266
        ],
        "scorePercentiles": {
          "0.0": 167.59033899115357,
          "50.0": 173.7625328211585,
          "90.0": 175.33693777062746,
          "95.0": 175.33693777062746,
          "99.0": 175.33693777062746,
          "99.9": 175.33693777062746,
          "99.99": 175.33693777062746,
          "99.999": 175.33693777062746,
          "99.9999": 175.33693777062746,
          "100.0": 175.33693777062746
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            167.59033899115357,
            172.440599075347,
            173.7625328211585,
            173.85657493223076,
            175.33693777062746
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day6Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 57444.81504622364,
        "scoreError": 5659.556278230832,
        "scoreConfidence": [
          51785.258767992804,
          63104.37132445447
        ],
        "scorePercentiles": {
          "0.0": 55098.23629843358,
          "50.0": 58240.00445578612,
          "90.0": 58638.88023863301,
          "95.0": 58638.88023863301,
          "99.0": 58638.88023863301,
          "99.9": 58638.88023863301,
          "99.99": 58638.88023863301,
          "99.999": 58638.88023863301,
          "99.9999": 58638.88023863301,
          "100.0": 58638.88023863301
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            56911.96772222648,
            58240.00445578612,
            58638.88023863301,
            55098.23629843358,
            58334.986516038996
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day6Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 55609.75090118272,
        "scoreError": 7106.330984254197,
        "scoreConfidence": [
          48503.41991692853,
          62716.08188543691
        ],
        "scorePercentiles": {
          "0.0": 52571.14157278005,
          "50.0": 55812.57739790974,
          "90.0": 57478.627022636916,
          "95.0": 57478.627022636916,
          "99.0": 57478.627022636916,
          "99.9": 57478.627022636916,
          "99.99": 57478.627022636916,
          "99.999": 57478.627022636916,
          "99.9999": 57478.627022636916,
          "100.0": 57478.627022636916
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            55652.22844142312,
            55812.57739790974,
            57478.627022636916,
            56534.18007116377,
            52571.14157278005
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day7Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4387.783845569841,
        "scoreError": 389.4074814576231,
        "scoreConfidence": [
          3998.376364112218,
          4777.1913270274645
        ],
        "scorePercentiles": {
          "0.0": 4258.998445118057,
          "50.0": 4391.365053566493,
          "90.0": 4515.388965448253,
          "95.0": 4515.388965448253,
          "99.0": 4515.388965448253,
          "99.9": 4515.388965448253,
          "99.99": 4515.388965448253,
          "99.999": 4515.388965448253,
          "99.9999": 4515.388965448253,
          "100.0": 4515.388965448253
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            4391.365053566493,
            4258.998445118057,
            4449.9195654304285,
            4515.388965448253,
            4323.247198285974
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day7Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 13357.18158921175,
        "scoreError": 457.35337281670064,
        "scoreConfidence": [
          12899.82821639505,
          13814.53496202845
        ],
        "scorePercentiles": {
          "0.0": 13185.038559388999,
          "50.0": 13376.567649863793,
          "90.0": 13466.533355050251,
          "95.0": 13466.533355050251,
          "99.0": 13466.533355050251,
          "99.9": 13466.533355050251,
          "99.99": 13466.533355050251,
          "99.999": 13466.533355050251,
          "99.9999": 13466.533355050251,
          "100.0": 13466.533355050251
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            13376.567649863793,
            13466.533355050251,
            13185.038559388999,
            13461.10174730006,
            13296.666634455652
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day8Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 20895.875935668813,
        "scoreError": 1749.3662807010173,
        "scoreConfidence": [
          19146.509654967795,
          22645.242216369832
        ],
        "scorePercentiles": {
          "0.0": 20417.005150333927,
          "50.0": 20890.483790761693,
          "90.0": 21478.478985007612,
          "95.0": 21478.478985007612,
          "99.0": 21478.478985007612,
          "99.9": 21478.478985007612,
          "99.99": 21478.478985007612,
          "99.999": 21478.478985007612,
          "99.9999": 21478.478985007612,
          "100.0": 21478.478985007612
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            21201.64505721415,
            20890.483790761693,
            20491.766695026672,
            20417.005150333927,
            21478.478985007612
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day8Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2056.1194030491106,
        "scoreError": 1759.774012710471,
        "scoreConfidence": [
          296.3453903386396,
          3815.8934157595813
        ],
        "scorePercentiles": {
          "0.0": 1243.399583361985,
          "50.0": 2262.571139294383,
          "90.0": 2324.7206783140755,
          "95.0": 2324.7206783140755,
          "99.0": 2324.7206783140755,
          "99.9": 2324.7206783140755,
          "99.99": 2324.7206783140755,
          "99.999": 2324.7206783140755,
          "99.9999": 2324.7206783140755,
          "100.0": 2324.7206783140755
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1243.399583361985,
            2262.571139294383,
            2324.7206783140755,
            2185.3780173770965,
            2264.5275968980113
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day9Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 9899.526860381575,
        "scoreError": 658.4644089301189,
        "scoreConfidence": [
          9241.062451451457,
          10557.991269311693
        ],
        "scorePercentiles": {
          "0.0": 9709.034959287485,
          "50.0": 9817.202980908585,
          "90.0": 10103.218197343289,
          "95.0": 10103.218197343289,
          "99.0": 10103.218197343289,
          "99.9": 10103.218197343289,
          "99.99": 10103.218197343289,
          "99.999": 10103.218197343289,
          "99.9999": 10103.218197343289,
          "100.0": 10103.218197343289
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            9811.569928552099,
            10056.60823581642,
            9709.034959287485,
            9817.202980908585,
            10103.218197343289
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day9Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 3256.941922019217,
        "scoreError": 178.6515081749427,
        "scoreConfidence": [
          3078.2904138442746,
          3435.5934301941597
        ],
        "scorePercentiles": {
          "0.0": 3203.293990379504,
          "50.0": 3260.746380789367,
          "90.0": 3310.8145426686106,
          "95.0": 3310.8145426686106,
          "99.0": 3310.8145426686106,
          "99.9": 3310.8145426686106,
          "99.99": 3310.8145426686106,
          "99.999": 3310.8145426686106,
          "99.9999": 3310.8145426686106,
          "100.0": 3310.8145426686106
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            3203.293990379504,
            3310.8145426686106,
            3292.3914541179697,
            3217.463242140636,
            3260.746380789367
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ]
};
