// provided.js - generated by ephemient/aoc2021/Kotlin benchmarks, 2021-12-12 09:18:30.513259869

var providedBenchmarks = ["jvmBench"];

var providedBenchmarkStore = {
  "jvmBench": [
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day10Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 8096.243152715283,
        "scoreError": 891.1207315783059,
        "scoreConfidence": [
          7205.122421136977,
          8987.363884293589
        ],
        "scorePercentiles": {
          "0.0": 7856.348972550721,
          "50.0": 8087.705031840927,
          "90.0": 8356.392583917064,
          "95.0": 8356.392583917064,
          "99.0": 8356.392583917064,
          "99.9": 8356.392583917064,
          "99.99": 8356.392583917064,
          "99.999": 8356.392583917064,
          "99.9999": 8356.392583917064,
          "100.0": 8356.392583917064
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            7879.606691999886,
            8356.392583917064,
            8301.162483267817,
            8087.705031840927,
            7856.348972550721
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day10Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 7065.898219262029,
        "scoreError": 651.3899066687567,
        "scoreConfidence": [
          6414.508312593272,
          7717.288125930785
        ],
        "scorePercentiles": {
          "0.0": 6877.713509932541,
          "50.0": 7130.269818637698,
          "90.0": 7220.52901271707,
          "95.0": 7220.52901271707,
          "99.0": 7220.52901271707,
          "99.9": 7220.52901271707,
          "99.99": 7220.52901271707,
          "99.999": 7220.52901271707,
          "99.9999": 7220.52901271707,
          "100.0": 7220.52901271707
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            7220.52901271707,
            6891.5507852105,
            6877.713509932541,
            7209.427969812326,
            7130.269818637698
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day11Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2980.919579867504,
        "scoreError": 228.3038251350761,
        "scoreConfidence": [
          2752.615754732428,
          3209.2234050025804
        ],
        "scorePercentiles": {
          "0.0": 2899.627140843361,
          "50.0": 2979.071092863463,
          "90.0": 3046.832721822277,
          "95.0": 3046.832721822277,
          "99.0": 3046.832721822277,
          "99.9": 3046.832721822277,
          "99.99": 3046.832721822277,
          "99.999": 3046.832721822277,
          "99.9999": 3046.832721822277,
          "100.0": 3046.832721822277
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2979.071092863463,
            2899.627140843361,
            3046.832721822277,
            2951.086799881621,
            3027.9801439267994
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day11Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2827.5779341587013,
        "scoreError": 53.759153374277155,
        "scoreConfidence": [
          2773.8187807844242,
          2881.3370875329783
        ],
        "scorePercentiles": {
          "0.0": 2816.260562626677,
          "50.0": 2819.0689421698935,
          "90.0": 2843.0313060127446,
          "95.0": 2843.0313060127446,
          "99.0": 2843.0313060127446,
          "99.9": 2843.0313060127446,
          "99.99": 2843.0313060127446,
          "99.999": 2843.0313060127446,
          "99.9999": 2843.0313060127446,
          "100.0": 2843.0313060127446
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2819.0689421698935,
            2816.9037709116083,
            2816.260562626677,
            2843.0313060127446,
            2842.6250890725833
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day12Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1168.652311189963,
        "scoreError": 115.18438647237666,
        "scoreConfidence": [
          1053.4679247175864,
          1283.8366976623397
        ],
        "scorePercentiles": {
          "0.0": 1118.361142907281,
          "50.0": 1177.5682419401185,
          "90.0": 1191.2035184442416,
          "95.0": 1191.2035184442416,
          "99.0": 1191.2035184442416,
          "99.9": 1191.2035184442416,
          "99.99": 1191.2035184442416,
          "99.999": 1191.2035184442416,
          "99.9999": 1191.2035184442416,
          "100.0": 1191.2035184442416
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            1166.1326357633677,
            1177.5682419401185,
            1118.361142907281,
            1191.2035184442416,
            1189.9960168948073
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day12Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 48.69654039589937,
        "scoreError": 3.696378227841407,
        "scoreConfidence": [
          45.00016216805796,
          52.392918623740776
        ],
        "scorePercentiles": {
          "0.0": 47.25556712593896,
          "50.0": 48.892833184565646,
          "90.0": 49.866592296739064,
          "95.0": 49.866592296739064,
          "99.0": 49.866592296739064,
          "99.9": 49.866592296739064,
          "99.99": 49.866592296739064,
          "99.999": 49.866592296739064,
          "99.9999": 49.866592296739064,
          "100.0": 49.866592296739064
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            48.892833184565646,
            49.04943389021997,
            49.866592296739064,
            48.4182754820332,
            47.25556712593896
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day1Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 20739.146588350566,
        "scoreError": 1943.3019427241204,
        "scoreConfidence": [
          18795.844645626446,
          22682.448531074686
        ],
        "scorePercentiles": {
          "0.0": 19863.545570516922,
          "50.0": 20989.99839004806,
          "90.0": 21047.45729877865,
          "95.0": 21047.45729877865,
          "99.0": 21047.45729877865,
          "99.9": 21047.45729877865,
          "99.99": 21047.45729877865,
          "99.999": 21047.45729877865,
          "99.9999": 21047.45729877865,
          "100.0": 21047.45729877865
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            20989.99839004806,
            19863.545570516922,
            21045.754953561416,
            21047.45729877865,
            20748.97672884777
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day1Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 12276.935335155122,
        "scoreError": 328.8669252318854,
        "scoreConfidence": [
          11948.068409923237,
          12605.802260387007
        ],
        "scorePercentiles": {
          "0.0": 12190.321896211126,
          "50.0": 12295.975330853837,
          "90.0": 12394.6113972538,
          "95.0": 12394.6113972538,
          "99.0": 12394.6113972538,
          "99.9": 12394.6113972538,
          "99.99": 12394.6113972538,
          "99.999": 12394.6113972538,
          "99.9999": 12394.6113972538,
          "100.0": 12394.6113972538
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            12307.603549590049,
            12295.975330853837,
            12196.1645018668,
            12394.6113972538,
            12190.321896211126
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day2Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 10444.75778276345,
        "scoreError": 961.4438596608628,
        "scoreConfidence": [
          9483.313923102587,
          11406.201642424314
        ],
        "scorePercentiles": {
          "0.0": 10133.853639665265,
          "50.0": 10503.121799620838,
          "90.0": 10747.559765306152,
          "95.0": 10747.559765306152,
          "99.0": 10747.559765306152,
          "99.9": 10747.559765306152,
          "99.99": 10747.559765306152,
          "99.999": 10747.559765306152,
          "99.9999": 10747.559765306152,
          "100.0": 10747.559765306152
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            10133.853639665265,
            10587.478458058931,
            10251.77525116607,
            10747.559765306152,
            10503.121799620838
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day2Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 10916.67837736338,
        "scoreError": 2917.6881945584178,
        "scoreConfidence": [
          7998.990182804962,
          13834.366571921797
        ],
        "scorePercentiles": {
          "0.0": 9928.72576579099,
          "50.0": 11019.47170418987,
          "90.0": 11864.149424546064,
          "95.0": 11864.149424546064,
          "99.0": 11864.149424546064,
          "99.9": 11864.149424546064,
          "99.99": 11864.149424546064,
          "99.999": 11864.149424546064,
          "99.9999": 11864.149424546064,
          "100.0": 11864.149424546064
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            11019.47170418987,
            11864.149424546064,
            11338.437832112584,
            10432.607160177384,
            9928.72576579099
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day3Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4201.595406798626,
        "scoreError": 601.295720177066,
        "scoreConfidence": [
          3600.29968662156,
          4802.891126975692
        ],
        "scorePercentiles": {
          "0.0": 3926.8397916225263,
          "50.0": 4244.115319151561,
          "90.0": 4303.492101246569,
          "95.0": 4303.492101246569,
          "99.0": 4303.492101246569,
          "99.9": 4303.492101246569,
          "99.99": 4303.492101246569,
          "99.999": 4303.492101246569,
          "99.9999": 4303.492101246569,
          "100.0": 4303.492101246569
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            3926.8397916225263,
            4244.115319151561,
            4303.492101246569,
            4240.675001095908,
            4292.854820876563
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day3Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 7752.330207374148,
        "scoreError": 664.3689786815341,
        "scoreConfidence": [
          7087.961228692614,
          8416.699186055683
        ],
        "scorePercentiles": {
          "0.0": 7548.606608594253,
          "50.0": 7774.33580235514,
          "90.0": 7929.250370135802,
          "95.0": 7929.250370135802,
          "99.0": 7929.250370135802,
          "99.9": 7929.250370135802,
          "99.99": 7929.250370135802,
          "99.999": 7929.250370135802,
          "99.9999": 7929.250370135802,
          "100.0": 7929.250370135802
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            7603.446561974663,
            7548.606608594253,
            7929.250370135802,
            7906.011693810881,
            7774.33580235514
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day4Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1629.444741706237,
        "scoreError": 1538.601953113641,
        "scoreConfidence": [
          90.84278859259598,
          3168.046694819878
        ],
        "scorePercentiles": {
          "0.0": 917.5180549402312,
          "50.0": 1805.347957062304,
          "90.0": 1858.4741233364216,
          "95.0": 1858.4741233364216,
          "99.0": 1858.4741233364216,
          "99.9": 1858.4741233364216,
          "99.99": 1858.4741233364216,
          "99.999": 1858.4741233364216,
          "99.9999": 1858.4741233364216,
          "100.0": 1858.4741233364216
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            917.5180549402312,
            1757.7805116455577,
            1808.1030615466707,
            1805.347957062304,
            1858.4741233364216
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day4Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1656.3979610600836,
        "scoreError": 1740.1698523160517,
        "scoreConfidence": [
          -83.77189125596806,
          3396.5678133761353
        ],
        "scorePercentiles": {
          "0.0": 848.7789847575443,
          "50.0": 1860.4875381756456,
          "90.0": 1875.1357306808784,
          "95.0": 1875.1357306808784,
          "99.0": 1875.1357306808784,
          "99.9": 1875.1357306808784,
          "99.99": 1875.1357306808784,
          "99.999": 1875.1357306808784,
          "99.9999": 1875.1357306808784,
          "100.0": 1875.1357306808784
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            848.7789847575443,
            1824.9723562412282,
            1872.6151954451227,
            1875.1357306808784,
            1860.4875381756456
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day5Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 477.801629915766,
        "scoreError": 30.665712257884255,
        "scoreConfidence": [
          447.13591765788175,
          508.46734217365025
        ],
        "scorePercentiles": {
          "0.0": 469.6205528814114,
          "50.0": 474.1953076339762,
          "90.0": 488.9327839216262,
          "95.0": 488.9327839216262,
          "99.0": 488.9327839216262,
          "99.9": 488.9327839216262,
          "99.99": 488.9327839216262,
          "99.999": 488.9327839216262,
          "99.9999": 488.9327839216262,
          "100.0": 488.9327839216262
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            469.6205528814114,
            474.1953076339762,
            483.11142812670084,
            488.9327839216262,
            473.14807701511506
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day5Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 163.96310950274125,
        "scoreError": 31.740323937404924,
        "scoreConfidence": [
          132.22278556533632,
          195.70343344014617
        ],
        "scorePercentiles": {
          "0.0": 154.35420331421338,
          "50.0": 165.2727889857315,
          "90.0": 172.91241432894512,
          "95.0": 172.91241432894512,
          "99.0": 172.91241432894512,
          "99.9": 172.91241432894512,
          "99.99": 172.91241432894512,
          "99.999": 172.91241432894512,
          "99.9999": 172.91241432894512,
          "100.0": 172.91241432894512
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            156.65840871940873,
            154.35420331421338,
            172.91241432894512,
            165.2727889857315,
            170.61773216540752
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day6Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 50682.79586876345,
        "scoreError": 5632.223448419497,
        "scoreConfidence": [
          45050.57242034395,
          56315.01931718295
        ],
        "scorePercentiles": {
          "0.0": 49368.39467474972,
          "50.0": 49787.40210065299,
          "90.0": 52536.84985527082,
          "95.0": 52536.84985527082,
          "99.0": 52536.84985527082,
          "99.9": 52536.84985527082,
          "99.99": 52536.84985527082,
          "99.999": 52536.84985527082,
          "99.9999": 52536.84985527082,
          "100.0": 52536.84985527082
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            52536.84985527082,
            49736.511569043534,
            49787.40210065299,
            51984.82114410023,
            49368.39467474972
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day6Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 52550.55938123142,
        "scoreError": 4602.816360446667,
        "scoreConfidence": [
          47947.74302078475,
          57153.375741678086
        ],
        "scorePercentiles": {
          "0.0": 51217.40068336628,
          "50.0": 52652.13647433774,
          "90.0": 54259.71019501751,
          "95.0": 54259.71019501751,
          "99.0": 54259.71019501751,
          "99.9": 54259.71019501751,
          "99.99": 54259.71019501751,
          "99.999": 54259.71019501751,
          "99.9999": 54259.71019501751,
          "100.0": 54259.71019501751
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            51643.77122652645,
            52652.13647433774,
            52979.778326909116,
            51217.40068336628,
            54259.71019501751
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day7Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 4163.039220647457,
        "scoreError": 180.39144257886733,
        "scoreConfidence": [
          3982.64777806859,
          4343.430663226324
        ],
        "scorePercentiles": {
          "0.0": 4108.927461303142,
          "50.0": 4148.037387868341,
          "90.0": 4219.793382004898,
          "95.0": 4219.793382004898,
          "99.0": 4219.793382004898,
          "99.9": 4219.793382004898,
          "99.99": 4219.793382004898,
          "99.999": 4219.793382004898,
          "99.9999": 4219.793382004898,
          "100.0": 4219.793382004898
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            4108.927461303142,
            4148.037387868341,
            4135.101145013805,
            4203.336727047097,
            4219.793382004898
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day7Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 11910.653747467653,
        "scoreError": 1806.2370366393884,
        "scoreConfidence": [
          10104.416710828265,
          13716.890784107041
        ],
        "scorePercentiles": {
          "0.0": 11264.501224846945,
          "50.0": 11844.596287840695,
          "90.0": 12426.983738027095,
          "95.0": 12426.983738027095,
          "99.0": 12426.983738027095,
          "99.9": 12426.983738027095,
          "99.99": 12426.983738027095,
          "99.999": 12426.983738027095,
          "99.9999": 12426.983738027095,
          "100.0": 12426.983738027095
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            11714.94093895197,
            12302.246547671566,
            11844.596287840695,
            11264.501224846945,
            12426.983738027095
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day8Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 20016.600656438528,
        "scoreError": 713.0480271297068,
        "scoreConfidence": [
          19303.552629308822,
          20729.648683568234
        ],
        "scorePercentiles": {
          "0.0": 19766.39615249541,
          "50.0": 20003.71786655158,
          "90.0": 20200.538314551188,
          "95.0": 20200.538314551188,
          "99.0": 20200.538314551188,
          "99.9": 20200.538314551188,
          "99.99": 20200.538314551188,
          "99.999": 20200.538314551188,
          "99.9999": 20200.538314551188,
          "100.0": 20200.538314551188
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            19766.39615249541,
            20200.538314551188,
            20192.973511586093,
            19919.377437008367,
            20003.71786655158
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day8Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 1888.0367727866014,
        "scoreError": 2001.0370645853225,
        "scoreConfidence": [
          -113.00029179872104,
          3889.073837371924
        ],
        "scorePercentiles": {
          "0.0": 960.0801498062758,
          "50.0": 2116.3596867964643,
          "90.0": 2157.892420715112,
          "95.0": 2157.892420715112,
          "99.0": 2157.892420715112,
          "99.9": 2157.892420715112,
          "99.99": 2157.892420715112,
          "99.999": 2157.892420715112,
          "99.9999": 2157.892420715112,
          "100.0": 2157.892420715112
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            960.0801498062758,
            2073.0351244107737,
            2157.892420715112,
            2116.3596867964643,
            2132.8164822043805
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day9Bench.part1",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 9331.607223725912,
        "scoreError": 921.6804309830366,
        "scoreConfidence": [
          8409.926792742875,
          10253.287654708949
        ],
        "scorePercentiles": {
          "0.0": 9000.894509450982,
          "50.0": 9443.764075529949,
          "90.0": 9542.347649930174,
          "95.0": 9542.347649930174,
          "99.0": 9542.347649930174,
          "99.9": 9542.347649930174,
          "99.99": 9542.347649930174,
          "99.999": 9542.347649930174,
          "99.9999": 9542.347649930174,
          "100.0": 9542.347649930174
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            9000.894509450982,
            9158.34851120274,
            9512.681372515715,
            9542.347649930174,
            9443.764075529949
          ]
        ]
      },
      "secondaryMetrics": {}
    },
    {
      "jmhVersion": "1.21",
      "benchmark": "com.github.ephemient.aoc2021.Day9Bench.part2",
      "mode": "thrpt",
      "threads": 1,
      "forks": 1,
      "jvm": "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64/bin/java",
      "jvmArgs": [
        "-Dfile.encoding=UTF-8",
        "-Duser.country",
        "-Duser.language=en",
        "-Duser.variant"
      ],
      "jdkVersion": "17.0.1",
      "vmName": "OpenJDK 64-Bit Server VM",
      "vmVersion": "17.0.1+12",
      "warmupIterations": 1,
      "warmupTime": "1 s",
      "warmupBatchSize": 1,
      "measurementIterations": 5,
      "measurementTime": "1 s",
      "measurementBatchSize": 1,
      "primaryMetric": {
        "score": 2965.1285686067795,
        "scoreError": 202.40288222386513,
        "scoreConfidence": [
          2762.7256863829143,
          3167.5314508306446
        ],
        "scorePercentiles": {
          "0.0": 2899.561809985951,
          "50.0": 2959.65018937848,
          "90.0": 3046.3675369352472,
          "95.0": 3046.3675369352472,
          "99.0": 3046.3675369352472,
          "99.9": 3046.3675369352472,
          "99.99": 3046.3675369352472,
          "99.999": 3046.3675369352472,
          "99.9999": 3046.3675369352472,
          "100.0": 3046.3675369352472
        },
        "scoreUnit": "ops/s",
        "rawData": [
          [
            2899.561809985951,
            2954.0777240603584,
            3046.3675369352472,
            2965.9855826738585,
            2959.65018937848
          ]
        ]
      },
      "secondaryMetrics": {}
    }
  ]
};
