name: Get inputs

on:
  workflow_call:
    secrets:
      SESSION:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Day
        id: get-day
        run: |
          from datetime import datetime, timedelta, tzinfo
          class TZ(tzinfo):
              def utcoffset(self, dt):
                  return timedelta(hours=-5) + self.dst(dt)
              def dst(self, dt):
                  return timedelta(0)
          day = (datetime.now(TZ()) - datetime(2021, 12, 1, 0, 0, 0, 0, TZ())).days + 1
          print("::set-output name=day::" + str(min(25, max(0, day))))
        shell: python
      - uses: actions/cache@v2
        with:
          key: inputs-${{ steps.get-day.outputs.day }}
          restore-keys: inputs-
          path: day*.txt
      - run: ./get-inputs.main.kts
        env:
          SESSION: ${{ secrets.SESSION }}
      - uses: actions/upload-artifact@v2
        with:
          name: inputs
          path: day*.txt
