name: Haskell docs

on:
  workflow_dispatch:

jobs:
  get-inputs:
    uses: ephemient/aoc2021/.github/workflows/get-inputs.yml@main
    secrets:
      SESSION: ${{ secrets.SESSION }}

  build:
    needs: [ get-inputs ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: gh-docs
          path: gh-docs
      - uses: actions/download-artifact@v2
        with:
          name: inputs
          path: hs
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-haddock-${{ hashFiles('**/stack.*') }}-${{ hashFiles('**/package.yaml') }}
          restore-keys: ${{ runner.os }}-haddock-${{ hashFiles('**/stack.*') }}-
          path: ~/.stack
      - run: stack haddock --only-dependencies
        working-directory: hs
      - run: stack haddock --only-locals --haddock-internal --haddock-arguments --ignore-all-exports
        working-directory: hs
      - run: rsync --archive --delete --verbose --whole-file hs/.stack-work/dist/*/*/doc/html/aoc2021/* gh-docs/haddock/
      - name: Rewrite links to Hackage
        run: find gh-docs/haddock -name '*.html' -print0 | xargs -0r sed -i -e 's!"\.\./\([^"/]\+\)/!"https://hackage.haskell.org/package/\1/docs/!g'
      - uses: EndBug/add-and-commit@v7
        with:
          cwd: gh-docs
          branch: gh-docs
          add: haddock
          message: 'Haddock ${{ github.sha }}'
