name: Kotlin benchmarks

on:
  workflow_dispatch:

jobs:
  get-inputs:
    uses: ephemient/aoc2021/.github/workflows/get-inputs.yml@main
    secrets:
      SESSION: ${{ secrets.SESSION }}

  build:
    needs: [ get-inputs ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: gh-docs
          path: gh-docs
      - uses: actions/download-artifact@v2
        with:
          name: inputs
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/*gradle*') }}
          path: ~/.gradle
      - run: ./gradlew --no-daemon --info benchmark
        working-directory: kt
      - run: rsync --archive --delete --verbose --whole-file kt/build/reports/benchmarks/main/*/*.json gh-docs/_data/benchmarks/
      - uses: EndBug/add-and-commit@v7
        with:
          cwd: gh-docs
          branch: gh-docs
          add: _data/benchmarks
          message: 'kotlinx.benchmark ${{ github.sha }}'
