name: Kotlin CI

on:
  push:
    branches: [ main ]
    paths: [ kt/** ]
  pull_request:
    branches: [ main ]
    paths: [ kt/** ]

  workflow_dispatch:

jobs:
  get-inputs:
    uses: ephemient/aoc2021/.github/workflows/get-inputs.yml@main
    secrets:
      SESSION: ${{ secrets.SESSION }}

  build:
    needs: [ get-inputs ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: inputs
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - run: ./gradlew --no-daemon --info build assembleBenchmarks
        working-directory: kt

  gradle-wrapper-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
